import mongoose from "mongoose";
import dotenv from "dotenv";
import CategoryAttribute from "../models/CategoryAttribute.js";

dotenv.config();

const CATEGORY_ATTRIBUTES = [
  {
    mainCategory: "Electronics",
    subCategory: "Mobiles & Accessories",
    subSubCategory: "Mobiles",
    fields: [
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Apple",
          "Samsung",
          "Xiaomi",
          "Oppo",
          "Vivo",
          "Huawei",
          "OnePlus",
          "Google",
          "Sony",
          "Motorola",
          "Nokia",
          "Realme",
          "Infinix",
          "Tecno",
          "iQOO",
          "Lava",
          "Micromax",
          "Asus",
          "ZTE",
          "Black Shark",
          "Honor",
          "POCO",
          "Itel",
          "Nothing",
          "Lenovo",
          "LG",
          "HTC",
          "Gionee",
          "Coolpad",
          "Karbonn",
          "Meizu",
          "Alcatel",
        ],
        displayOrder: 1,
        placeholder: "Select a brand",
        helpText: "Choose the device manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 2,
        placeholder: "e.g., iPhone 15 Pro Max",
        helpText: "Enter the exact model name",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "White",
          "Blue",
          "Red",
          "Green",
          "Gold",
          "Silver",
          "Grey",
          "Purple",
          "Pink",
          "Yellow",
          "Orange",
          "Cream",
          "Violet",
          "Bronze",
          "Turquoise",
          "Midnight",
          "Starlight",
          "Graphite",
          "Sierra Blue",
          "Deep Purple",
          "Space Black",
          "Titanium",
        ],
        displayOrder: 3,
        placeholder: "Select color",
        helpText: "Choose the device color",
      },
      {
        fieldName: "RAM Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "512MB",
          "1GB",
          "2GB",
          "3GB",
          "4GB",
          "6GB",
          "8GB",
          "12GB",
          "16GB",
          "18GB",
          "24GB",
        ],
        displayOrder: 4,
        placeholder: "Select RAM",
        helpText: "Device RAM memory",
      },
      {
        fieldName: "Internal Storage",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "32MB",
          "64MB",
          "128MB",
          "256MB",
          "512MB",
          "4GB",
          "8GB",
          "16GB",
          "32GB",
          "64GB",
          "128GB",
          "256GB",
          "512GB",
          "1TB",
        ],
        displayOrder: 5,
        placeholder: "Select storage",
        helpText: "Internal storage capacity",
      },
      {
        fieldName: "Screen Size",
        dataType: "Decimal",
        required: true,
        filterable: true,
        displayOrder: 6,
        placeholder: "e.g., 6.1",
        helpText: "Display size in inches",
      },
      {
        fieldName: "Network Type",
        dataType: "Multi-Select",
        required: true,
        filterable: true,
        options: ["2G", "3G", "4G", "4G VoLTE", "5G"],
        displayOrder: 7,
        placeholder: "Select network types",
        helpText: "Supported network bands",
      },
      {
        fieldName: "Operating System",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Android",
          "iOS",
          "Windows",
          "Feature Phone OS",
          "Symbian",
          "Tizen",
          "KaiOS",
          "HarmonyOS",
        ],
        displayOrder: 8,
        placeholder: "Select OS",
        helpText: "Device operating system",
      },
      {
        fieldName: "Primary Camera",
        dataType: "Text",
        required: true,
        filterable: true,
        displayOrder: 9,
        placeholder: "e.g., 50MP + 12MP + 10MP",
        helpText: "Rear camera specifications",
      },
      {
        fieldName: "Secondary Camera",
        dataType: "Text",
        required: false,
        filterable: true,
        displayOrder: 10,
        placeholder: "e.g., 12MP Front Camera",
        helpText: "Front camera specifications",
      },
      {
        fieldName: "Battery Capacity",
        dataType: "Integer",
        required: true,
        filterable: true,
        displayOrder: 11,
        placeholder: "e.g., 5000",
        helpText: "Battery capacity in mAh",
      },
      {
        fieldName: "Processor Brand",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Apple A-Series",
          "Qualcomm Snapdragon",
          "MediaTek Dimensity",
          "MediaTek Helio",
          "Samsung Exynos",
          "Google Tensor",
          "HiSilicon Kirin",
          "Unisoc",
        ],
        displayOrder: 12,
        placeholder: "Select processor",
        helpText: "CPU manufacturer and series",
      },
      {
        fieldName: "Processor Speed",
        dataType: "Text",
        required: false,
        filterable: false,
        displayOrder: 13,
        placeholder: "e.g., 3.2 GHz",
        helpText: "Maximum processor frequency",
      },
      {
        fieldName: "Resolution Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "QVGA",
          "HD",
          "HD+",
          "Full HD",
          "Full HD+",
          "Quad HD",
          "Quad HD+",
          "4K",
          "Retina Display",
          "Super Retina XDR",
        ],
        displayOrder: 14,
        placeholder: "Select resolution",
        helpText: "Display resolution type",
      },
      {
        fieldName: "SIM Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["Single SIM", "Dual SIM", "Hybrid Slot", "eSIM"],
        displayOrder: 15,
        placeholder: "Select SIM type",
        helpText: "SIM card configuration",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 16,
        placeholder: "e.g., 1 Year Manufacturer Warranty",
        helpText: "Warranty information",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 17,
        placeholder: "e.g., Handset,Power Adapter,USB Cable",
        helpText: "Items included in the box",
      },
    ],
  },

  // ============ ELECTRONICS > MOBILES & ACCESSORIES > TABLETS ============
  {
    mainCategory: "Electronics",
    subCategory: "Mobiles & Accessories",
    subSubCategory: "Tablets",
    fields: [
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Apple",
          "Samsung",
          "Lenovo",
          "Xiaomi",
          "Realme",
          "OnePlus",
          "Honor",
          "Huawei",
          "Nokia",
          "Motorola",
          "Amazon",
          "Microsoft",
          "Google",
          "Asus",
          "Acer",
          "Dell",
          "HP",
          "Alcatel",
          "TCL",
          "Lava",
          "Micromax",
          "iBall",
          "Swipe",
          "Fusion5",
          "Teclast",
          "Chuwi",
        ],
        displayOrder: 1,
        placeholder: "Select a brand",
        helpText: "Choose the tablet manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 2,
        placeholder: "e.g., iPad Air 5th Gen, Galaxy Tab S9",
        helpText: "Enter the exact model name",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "White",
          "Silver",
          "Grey",
          "Gold",
          "Rose Gold",
          "Blue",
          "Green",
          "Pink",
          "Purple",
          "Graphite",
          "Space Grey",
          "Starlight",
          "Midnight",
          "Mint",
          "Teal",
          "Lavender",
          "Mystic Bronze",
          "Mystic Silver",
          "Storm Grey",
          "Frost Blue",
        ],
        displayOrder: 3,
        placeholder: "Select color",
        helpText: "Choose the tablet color",
      },
      {
        fieldName: "RAM Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["1GB", "2GB", "3GB", "4GB", "6GB", "8GB", "12GB", "16GB", "32GB"],
        displayOrder: 4,
        placeholder: "Select RAM",
        helpText: "Tablet RAM memory",
      },
      {
        fieldName: "Internal Storage",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["8GB", "16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB"],
        displayOrder: 5,
        placeholder: "Select storage",
        helpText: "Internal storage capacity",
      },
      {
        fieldName: "Screen Size",
        dataType: "Decimal",
        required: true,
        filterable: true,
        displayOrder: 6,
        placeholder: "e.g., 8.3, 10.2, 12.9",
        helpText: "Display size in inches",
      },
      {
        fieldName: "Connectivity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["Wi-Fi Only", "Wi-Fi + 4G", "Wi-Fi + 5G", "Wi-Fi + Cellular"],
        displayOrder: 7,
        placeholder: "Select connectivity type",
        helpText: "Network connectivity options",
      },
      {
        fieldName: "Operating System",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["iPadOS", "Android", "Windows", "Chrome OS", "Fire OS", "HarmonyOS"],
        displayOrder: 8,
        placeholder: "Select OS",
        helpText: "Tablet operating system",
      },
      {
        fieldName: "Voice Call Support",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 9,
        placeholder: "Select option",
        helpText: "Can this tablet make voice calls?",
      },
      {
        fieldName: "Battery Capacity",
        dataType: "Integer",
        required: true,
        filterable: true,
        displayOrder: 10,
        placeholder: "e.g., 7040",
        helpText: "Battery capacity in mAh",
      },
      {
        fieldName: "Primary Camera",
        dataType: "Text",
        required: true,
        filterable: true,
        displayOrder: 11,
        placeholder: "e.g., 13MP, 12MP Wide",
        helpText: "Rear camera specifications",
      },
      {
        fieldName: "Front Camera",
        dataType: "Text",
        required: false,
        filterable: true,
        displayOrder: 12,
        placeholder: "e.g., 12MP Ultra Wide",
        helpText: "Front camera specifications",
      },
      {
        fieldName: "Processor Brand",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Apple M-Series",
          "Apple A-Series",
          "Qualcomm Snapdragon",
          "MediaTek Helio",
          "MediaTek Dimensity",
          "Samsung Exynos",
          "Intel Core",
          "Intel Pentium",
          "Microsoft SQ",
          "Unisoc",
        ],
        displayOrder: 13,
        placeholder: "Select processor",
        helpText: "CPU manufacturer and series",
      },
      {
        fieldName: "Display Resolution Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["HD", "Full HD", "2K", "4K", "Liquid Retina", "Super AMOLED", "IPS LCD", "PixelSense"],
        displayOrder: 14,
        placeholder: "Select resolution",
        helpText: "Display resolution type",
      },
      {
        fieldName: "Stylus Included",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 15,
        placeholder: "Select option",
        helpText: "Is a stylus included with the tablet?",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 16,
        placeholder: "e.g., 1 Year Manufacturer Warranty",
        helpText: "Warranty information",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 17,
        placeholder: "e.g., Tablet, USB-C Cable, 20W Adapter, S-Pen",
        helpText: "Items included in the box",
      },
    ],
  },

  // ============ ELECTRONICS > MOBILES & ACCESSORIES > MOBILE ACCESSORIES ============
  {
    mainCategory: "Electronics",
    subCategory: "Mobiles & Accessories",
    subSubCategory: "Mobile Accessories",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Back Cover",
          "Flip Cover",
          "Bumper Case",
          "Screen Guard",
          "Tempered Glass",
          "Camera Lens Protector",
          "Wall Charger",
          "Car Charger",
          "Wireless Charger",
          "MagSafe Charger",
          "Data Cable",
          "Power Bank",
          "Mobile Holder",
          "Pop Socket",
          "Selfie Stick",
          "Mobile Skin",
          "OTG Adapter",
          "SIM Ejector Pin",
          "Stylus",
        ],
        displayOrder: 1,
        placeholder: "Select accessory type",
        helpText: "Choose the type of mobile accessory",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Spigen",
          "OtterBox",
          "Boat",
          "Portronics",
          "Ambrane",
          "Mi",
          "Realme",
          "Samsung",
          "Apple",
          "OnePlus",
          "UBON",
          "Zebronics",
          "pTron",
          "Urbn",
          "Belkin",
          "Stuffcool",
          "Ringke",
          "Caseology",
          "Nillkin",
          "ESR",
          "Supcase",
          "DailyObjects",
          "Kapaver",
          "Mobiz",
          "Hontinga",
          "Flipkart SmartBuy",
          "AmazonBasics",
          "Duracell",
          "Anker",
          "Aukey",
          "Baseus",
        ],
        displayOrder: 2,
        placeholder: "Select brand",
        helpText: "Choose the accessory brand",
      },
      {
        fieldName: "Compatible Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Apple",
          "Samsung",
          "Xiaomi",
          "Oppo",
          "Vivo",
          "OnePlus",
          "Google",
          "Realme",
          "Motorola",
          "Nokia",
          "Huawei",
          "Honor",
          "Asus",
          "Sony",
          "Tecno",
          "Infinix",
          "iQOO",
          "Nothing",
          "Universal",
        ],
        displayOrder: 3,
        placeholder: "Select phone brand",
        helpText: "Which phone brand is this accessory compatible with?",
      },
      {
        fieldName: "Compatible Model",
        dataType: "Multi-Select",
        required: true,
        filterable: true,
        options: [
          "iPhone 13",
          "iPhone 14",
          "iPhone 15",
          "Galaxy S21",
          "Galaxy S22",
          "Galaxy S23",
          "Galaxy S24",
          "Redmi Note 10 Pro",
          "Redmi Note 11 Pro",
          "Redmi Note 12 Pro",
          "Oppo A53",
          "Oppo A54",
          "Vivo Y33s",
          "Vivo Y73",
          "OnePlus 9",
          "OnePlus 11",
          "Google Pixel 6",
          "Google Pixel 7",
          "Realme 8",
          "Realme 9",
          "Motorola G51",
          "Motorola E40",
          "Universal",
        ],
        displayOrder: 4,
        placeholder: "Select compatible models",
        helpText: "Which phone models is this compatible with?",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Transparent",
          "Black",
          "White",
          "Blue",
          "Red",
          "Green",
          "Pink",
          "Purple",
          "Gold",
          "Silver",
          "Grey",
          "Yellow",
          "Orange",
          "Brown",
          "Beige",
          "Multicolor",
          "Patterned",
          "Matte Black",
          "Carbon Fiber",
        ],
        displayOrder: 5,
        placeholder: "Select color",
        helpText: "Choose the accessory color",
      },
      {
        fieldName: "Material",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Silicon",
          "TPU (Thermoplastic Polyurethane)",
          "Polycarbonate",
          "Leather",
          "Artificial Leather",
          "Rubber",
          "Plastic",
          "Glass",
          "Metal",
          "Fabric",
          "Nylon Braided",
          "TPE",
          "Wood",
        ],
        displayOrder: 6,
        placeholder: "Select material",
        helpText: "What material is the accessory made of?",
      },
      {
        fieldName: "Connectivity Interface",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Micro USB",
          "USB Type-C",
          "Lightning",
          "USB Type-A",
          "Wireless",
          "MagSafe",
          "3.5mm Audio Jack",
        ],
        displayOrder: 7,
        placeholder: "Select interface",
        helpText: "Connection type (if applicable)",
      },
      {
        fieldName: "Cable Length",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["0.2m", "0.5m", "1m", "1.2m", "1.5m", "2m", "3m", ">3m"],
        displayOrder: 8,
        placeholder: "Select length",
        helpText: "Cable length in meters (if applicable)",
      },
      {
        fieldName: "Power Output",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "5W",
          "10W",
          "12W",
          "15W",
          "18W",
          "20W",
          "25W",
          "27W",
          "30W",
          "33W",
          "45W",
          "60W",
          "65W",
          "80W",
          "100W",
          "120W",
        ],
        displayOrder: 9,
        placeholder: "Select power output",
        helpText: "Charger power output in watts (if applicable)",
      },
      {
        fieldName: "Power Bank Capacity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["5000 mAh", "10000 mAh", "20000 mAh", "30000 mAh", ">30000 mAh"],
        displayOrder: 10,
        placeholder: "Select capacity",
        helpText: "Power bank capacity in mAh (if applicable)",
      },
      {
        fieldName: "Theme/Pattern",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "3D Design",
          "Abstract",
          "Animals",
          "Anime",
          "Automotive",
          "Cartoons",
          "Floral",
          "Geometric",
          "Marble",
          "Quotes",
          "Solid",
          "Superheroes",
          "Transparent",
          "Vintage",
          "Wood Grain",
        ],
        displayOrder: 11,
        placeholder: "Select theme",
        helpText: "Design pattern or theme",
      },
      {
        fieldName: "Features",
        dataType: "Multi-Select",
        required: false,
        filterable: true,
        options: [
          "Fast Charging",
          "Quick Charge 3.0",
          "Power Delivery (PD)",
          "MagSafe Compatible",
          "Kickstand",
          "Card Slot",
          "Shockproof",
          "Waterproof",
          "Magnetic",
          "LED Indicator",
          "Braided Cable",
          "Reversible Connector",
          "Multi-Port",
        ],
        displayOrder: 12,
        placeholder: "Select features",
        helpText: "Special features of the accessory",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 13,
        placeholder: "e.g., 6 Months Replacement Warranty",
        helpText: "Warranty information",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 14,
        placeholder: "e.g., 1 x Back Cover",
        helpText: "Items included in the package",
      },
    ],
  },

  // ============ ELECTRONICS > MOBILES & ACCESSORIES > TABLET ACCESSORIES ============
  {
    mainCategory: "Electronics",
    subCategory: "Mobiles & Accessories",
    subSubCategory: "Tablet Accessories",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Flip Cover",
          "Back Cover",
          "Keyboard Case",
          "Book Cover",
          "Screen Guard",
          "Tempered Glass",
          "Stylus / Pencil",
          "Tablet Stand",
          "Sleeve / Pouch",
          "Car Mount",
          "Charger",
          "Cable",
        ],
        displayOrder: 1,
        placeholder: "Select accessory type",
        helpText: "Choose the type of tablet accessory",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Apple",
          "Samsung",
          "Spigen",
          "ESR",
          "Logitech",
          "ProElite",
          "Robustrion",
          "OtterBox",
          "Targus",
          "UAG",
          "Ringke",
          "Nillkin",
          "Hama",
          "Belkin",
          "Zebronics",
          "Portronics",
          "Tukzer",
          "Maring",
          "DailyObjects",
          "AmazonBasics",
        ],
        displayOrder: 2,
        placeholder: "Select brand",
        helpText: "Choose the accessory brand",
      },
      {
        fieldName: "Compatible Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Apple",
          "Samsung",
          "Lenovo",
          "Xiaomi",
          "Realme",
          "OnePlus",
          "Huawei",
          "Honor",
          "Microsoft",
          "Amazon",
          "Google",
          "Asus",
          "Dell",
          "HP",
          "Acer",
          "Nokia",
          "Motorola",
          "Universal",
        ],
        displayOrder: 3,
        placeholder: "Select tablet brand",
        helpText: "Which tablet brand is this compatible with?",
      },
      {
        fieldName: "Compatible Model",
        dataType: "Multi-Select",
        required: true,
        filterable: true,
        options: [
          "iPad Pro 12.9 (2022)",
          "iPad Air 5th Gen",
          "iPad 10th Gen",
          "iPad Mini 6th Gen",
          "Galaxy Tab S9 Ultra",
          "Galaxy Tab S9",
          "Galaxy Tab A8",
          "Galaxy Tab S8",
          "Lenovo Tab M10",
          "Lenovo Tab P11",
          "Xiaomi Pad 6",
          "Realme Pad X",
          "Surface Pro 9",
          "Surface Go 4",
          "Huawei MatePad Pro",
          "Honor Pad 8",
          "Amazon Fire HD 10",
          "Google Pixel Tablet",
          "Asus ZenPad",
          "Dell Tablet",
          "HP Tablet",
          "Acer Tablet",
          "Universal 7-inch",
          "Universal 10-inch",
        ],
        displayOrder: 4,
        placeholder: "Select compatible models",
        helpText: "Which tablet models is this compatible with?",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "Blue",
          "Grey",
          "Rose Gold",
          "Pink",
          "Green",
          "Purple",
          "Red",
          "White",
          "Silver",
          "Gold",
          "Brown",
          "Navy Blue",
          "Teal",
          "Lavender",
          "Transparent",
          "Multicolor",
          "Patterned",
        ],
        displayOrder: 5,
        placeholder: "Select color",
        helpText: "Choose the accessory color",
      },
      {
        fieldName: "Material",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Leather",
          "PU Leather (Artificial)",
          "Polyurethane",
          "Silicon",
          "TPU",
          "Polycarbonate",
          "Plastic",
          "Fabric",
          "Felt",
          "Aluminium",
          "Tempered Glass",
          "Nylon",
        ],
        displayOrder: 6,
        placeholder: "Select material",
        helpText: "What material is the accessory made of?",
      },
      {
        fieldName: "Case Style",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Folio",
          "Trifold",
          "Rugged / Armor",
          "Smart Cover",
          "Bumper",
          "Magnetic Attachment",
          "Shell",
          "Pouch",
        ],
        displayOrder: 7,
        placeholder: "Select case style",
        helpText: "What style of case is this?",
      },
      {
        fieldName: "Features",
        dataType: "Multi-Select",
        required: false,
        filterable: true,
        options: [
          "Auto Sleep / Wake",
          "Built-in Pencil Holder",
          "Rotating Stand (360 Degree)",
          "Kickstand",
          "Magnetic Closure",
          "Shockproof",
          "Waterproof",
          "Detachable Keyboard",
          "Backlit Keys",
          "Trackpad Included",
          "Anti-Glare (for Screen Guards)",
          "Paper-feel (for Screen Guards)",
        ],
        displayOrder: 8,
        placeholder: "Select features",
        helpText: "Special features of the accessory",
      },
      {
        fieldName: "Keyboard Connectivity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Bluetooth",
          "Smart Connector (Magnetic)",
          "USB-C",
          "USB Receiver",
          "Wired",
        ],
        displayOrder: 9,
        placeholder: "Select connectivity",
        helpText: "How does the keyboard connect? (if applicable)",
      },
      {
        fieldName: "Screen Size Compatibility",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "7 inch",
          "8 inch",
          "9.7 inch",
          "10.2 inch",
          "10.5 inch",
          "10.9 inch",
          "11 inch",
          "12.4 inch",
          "12.9 inch",
          "14.6 inch",
        ],
        displayOrder: 10,
        placeholder: "Select screen size",
        helpText: "Compatible tablet screen size",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 11,
        placeholder: "e.g., 1 Year Manufacturer Warranty",
        helpText: "Warranty information",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 12,
        placeholder: "e.g., 1 x Flip Cover",
        helpText: "Items included in the package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Laptops",
    fields: [
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "HP",
          "Dell",
          "Lenovo",
          "Asus",
          "Acer",
          "Apple",
          "MSI",
          "Samsung",
          "Microsoft",
          "Xiaomi",
          "Realme",
          "Infinix",
          "Honor",
          "Huawei",
          "LG",
          "Gigabyte",
          "Razer",
          "Fujitsu",
          "Avita",
          "Chuwi",
          "Vaio",
          "Nokia",
          "Zebronics",
          "Micromax",
          "iBall",
          "Lava",
          "Ultimus",
          "Wings",
          "Primebook",
        ],
        displayOrder: 1,
        placeholder: "Select a brand",
        helpText: "Laptop manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 2,
        placeholder: "e.g., MacBook Air M2, ROG Strix G15, Pavilion 15",
        helpText: "Specific model name of the laptop",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "Silver",
          "Grey",
          "White",
          "Blue",
          "Gold",
          "Rose Gold",
          "Red",
          "Green",
          "Pink",
          "Purple",
          "Gunmetal",
          "Dark Side of the Moon",
          "Lunar Light",
          "Storm Grey",
          "Midnight",
          "Starlight",
          "Space Grey",
          "Mecha Gray",
          "Eclipse Gray",
          "Graphite",
          "Transparent",
        ],
        displayOrder: 3,
        placeholder: "Select a color",
        helpText: "Laptop color/finish",
      },
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Thin and Light Laptop",
          "Gaming Laptop",
          "2-in-1 Laptop",
          "Business Laptop",
          "Creator Laptop",
          "Chromebook",
          "Mainstream Laptop",
        ],
        displayOrder: 4,
        placeholder: "Select laptop type",
        helpText: "Category of laptop based on use case",
      },
      {
        fieldName: "Processor Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Intel",
          "AMD",
          "Apple M-Series",
          "Qualcomm",
          "MediaTek",
        ],
        displayOrder: 5,
        placeholder: "Select processor brand",
        helpText: "Processor manufacturer",
      },
      {
        fieldName: "Processor Name",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Core i3",
          "Core i5",
          "Core i7",
          "Core i9",
          "Core Ultra 5",
          "Core Ultra 7",
          "Core Ultra 9",
          "Ryzen 3",
          "Ryzen 5",
          "Ryzen 7",
          "Ryzen 9",
          "Apple M1",
          "Apple M1 Pro",
          "Apple M1 Max",
          "Apple M2",
          "Apple M2 Pro",
          "Apple M2 Max",
          "Apple M3",
          "Apple M3 Pro",
          "Apple M3 Max",
          "Apple M4",
          "Snapdragon X Elite",
          "Snapdragon 7c Gen 2",
          "Pentium Gold",
          "Celeron",
          "Athlon",
        ],
        displayOrder: 6,
        placeholder: "Select processor",
        helpText: "Specific processor model",
      },
      {
        fieldName: "Processor Generation",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "14th Gen",
          "13th Gen",
          "12th Gen",
          "11th Gen",
          "10th Gen",
          "7000 Series",
          "6000 Series",
          "5000 Series",
          "4000 Series",
          "Not Applicable",
        ],
        displayOrder: 7,
        placeholder: "Select generation",
        helpText: "Processor generation/series",
      },
      {
        fieldName: "RAM Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "4GB",
          "8GB",
          "12GB",
          "16GB",
          "24GB",
          "32GB",
          "64GB",
          "96GB",
          "128GB",
        ],
        displayOrder: 8,
        placeholder: "Select RAM capacity",
        helpText: "Amount of RAM (Random Access Memory)",
      },
      {
        fieldName: "RAM Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "DDR4",
          "DDR5",
          "LPDDR4",
          "LPDDR4X",
          "LPDDR5",
          "LPDDR5X",
          "Unified Memory",
        ],
        displayOrder: 9,
        placeholder: "Select RAM type",
        helpText: "Type of RAM technology",
      },
      {
        fieldName: "SSD Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "128GB",
          "256GB",
          "512GB",
          "1TB",
          "2TB",
          "4TB",
          "8TB",
        ],
        displayOrder: 10,
        placeholder: "Select SSD capacity",
        helpText: "Storage capacity (SSD)",
      },
      {
        fieldName: "HDD Capacity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "No HDD",
          "500GB",
          "1TB",
          "2TB",
        ],
        displayOrder: 11,
        placeholder: "Select HDD capacity",
        helpText: "Secondary storage (HDD) if available",
      },
      {
        fieldName: "Graphic Processor Brand",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVIDIA",
          "AMD",
          "Intel",
          "Apple (Integrated)",
          "ARM (Qualcomm)",
        ],
        displayOrder: 12,
        placeholder: "Select GPU brand",
        helpText: "Graphics processor manufacturer",
      },
      {
        fieldName: "Graphic Processor Series",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVIDIA GeForce RTX 4090",
          "NVIDIA GeForce RTX 4080",
          "NVIDIA GeForce RTX 4070",
          "NVIDIA GeForce RTX 4060",
          "NVIDIA GeForce RTX 4050",
          "NVIDIA GeForce RTX 3080 Ti",
          "NVIDIA GeForce RTX 3070 Ti",
          "NVIDIA GeForce RTX 3060",
          "NVIDIA GeForce RTX 3050",
          "NVIDIA GeForce GTX 1650",
          "Intel Arc Graphics",
          "Intel Iris Xe",
          "Intel UHD",
          "AMD Radeon RX 7000 Series",
          "AMD Radeon RX 6000 Series",
          "AMD Radeon Vega",
          "Apple Integrated Graphics",
        ],
        displayOrder: 13,
        placeholder: "Select GPU series",
        helpText: "Specific GPU model series",
      },
      {
        fieldName: "Dedicated Graphic Memory",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Integrated",
          "2GB",
          "4GB",
          "6GB",
          "8GB",
          "10GB",
          "12GB",
          "16GB",
          "24GB",
        ],
        displayOrder: 14,
        placeholder: "Select GPU memory",
        helpText: "Amount of dedicated graphics memory (VRAM)",
      },
      {
        fieldName: "Operating System",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Windows 11 Home",
          "Windows 11 Pro",
          "Windows 10 Home",
          "Windows 10 Pro",
          "macOS Sonoma",
          "macOS Ventura",
          "macOS Monterey",
          "Chrome OS",
          "DOS",
          "Ubuntu",
          "Linux",
          "Prime OS",
        ],
        displayOrder: 15,
        placeholder: "Select OS",
        helpText: "Operating system",
      },
      {
        fieldName: "Touchscreen",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 16,
        placeholder: "Select option",
        helpText: "Does the laptop have a touchscreen display?",
      },
      {
        fieldName: "Screen Size",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "11.6 inch",
          "12.4 inch",
          "13.3 inch",
          "13.4 inch",
          "13.5 inch",
          "13.6 inch",
          "14 inch",
          "14.2 inch",
          "14.5 inch",
          "15.6 inch",
          "16 inch",
          "16.1 inch",
          "17.3 inch",
          "18 inch",
        ],
        displayOrder: 17,
        placeholder: "Select screen size",
        helpText: "Display diagonal size",
      },
      {
        fieldName: "Screen Resolution",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "HD (1366 x 768)",
          "Full HD (1920 x 1080)",
          "Full HD+ (1920 x 1200)",
          "Quad HD (2560 x 1440)",
          "2.8K (2880 x 1800)",
          "3K (3072 x 1920)",
          "4K Ultra HD (3840 x 2160)",
          "Liquid Retina XDR",
        ],
        displayOrder: 18,
        placeholder: "Select resolution",
        helpText: "Display pixel resolution",
      },
      {
        fieldName: "Screen Refresh Rate",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "60Hz",
          "90Hz",
          "120Hz",
          "144Hz",
          "165Hz",
          "240Hz",
          "300Hz",
          "360Hz",
          "480Hz",
        ],
        displayOrder: 19,
        placeholder: "Select refresh rate",
        helpText: "Display refresh rate for smooth scrolling",
      },
      {
        fieldName: "Backlit Keyboard",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 20,
        placeholder: "Select option",
        helpText: "Does the keyboard have backlighting?",
      },
      {
        fieldName: "Fingerprint Sensor",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 21,
        placeholder: "Select option",
        helpText: "Does the laptop have a fingerprint sensor?",
      },
      {
        fieldName: "Weight",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "< 1.0 kg",
          "1.0 kg - 1.5 kg",
          "1.5 kg - 2.0 kg",
          "2.0 kg - 2.5 kg",
          "> 2.5 kg",
        ],
        displayOrder: 22,
        placeholder: "Select weight range",
        helpText: "Laptop weight category",
      },
      {
        fieldName: "Battery Information",
        dataType: "Text",
        required: false,
        filterable: false,
        displayOrder: 23,
        placeholder: "e.g., 70 Whr, 4-cell Li-ion",
        helpText: "Battery capacity and type",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 24,
        placeholder: "e.g., 1 Year Onsite Warranty",
        helpText: "Warranty details and coverage",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 25,
        placeholder: "e.g., Laptop, Power Adapter, User Manual",
        helpText: "Items included in the package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Laptop Accessories",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Mouse",
          "Keyboard",
          "Laptop Bag",
          "Backpack",
          "Laptop Sleeve/Slipcase",
          "Laptop Skin",
          "Cooling Pad",
          "Laptop Stand",
          "Webcam",
          "USB Hub",
          "Docking Station",
          "Privacy Screen Filter",
          "Keyboard Protector",
          "Dust Plug",
          "Laptop Battery",
          "Laptop Adapter/Charger",
          "External DVD Writer",
          "Cable Lock",
        ],
        displayOrder: 1,
        placeholder: "Select accessory type",
        helpText: "Type of laptop accessory",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Logitech",
          "HP",
          "Dell",
          "Lenovo",
          "Razer",
          "Asus",
          "Zebronics",
          "Portronics",
          "Frontech",
          "Quantum",
          "Microsoft",
          "Apple",
          "Targus",
          "Samsonite",
          "American Tourister",
          "Skybags",
          "Wildcraft",
          "Arctic Fox",
          "Safari",
          "F Gear",
          "Wesley",
          "Cosmous",
          "Probus",
          "Tukzer",
          "Zinq",
          "Ant Esports",
          "Redgear",
          "Corsair",
          "HyperX",
          "SteelSeries",
          "Keychron",
          "Royal Kludge",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Accessory manufacturer",
      },
      {
        fieldName: "Compatible Laptop Size",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "11.6 inch",
          "13.3 inch",
          "14 inch",
          "15.6 inch",
          "16 inch",
          "17.3 inch",
          "Universal",
        ],
        displayOrder: 3,
        placeholder: "Select laptop size",
        helpText: "Compatible laptop screen size",
      },
      {
        fieldName: "Connectivity Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Wired",
          "Wireless (2.4GHz Dongle)",
          "Bluetooth",
          "Dual Mode (Wireless + Bluetooth)",
        ],
        displayOrder: 4,
        placeholder: "Select connectivity",
        helpText: "How the accessory connects to the laptop",
      },
      {
        fieldName: "Interface",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "USB Type-A",
          "USB Type-C",
          "Bluetooth",
          "PS/2",
          "3.5mm Jack",
        ],
        displayOrder: 5,
        placeholder: "Select interface",
        helpText: "Connection interface/port type",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "White",
          "Grey",
          "Silver",
          "Blue",
          "Red",
          "Pink",
          "Green",
          "Purple",
          "Yellow",
          "Orange",
          "Gold",
          "Rose Gold",
          "Multicolor",
          "Camouflage",
          "Transparent",
          "Patterned",
          "RGB (Lighting)",
        ],
        displayOrder: 6,
        placeholder: "Select a color",
        helpText: "Accessory color/finish",
      },
      {
        fieldName: "Material",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Nylon",
          "Polyester",
          "Leather",
          "PU Leather",
          "Neoprene",
          "Canvas",
          "Plastic",
          "Aluminium",
          "Metal Mesh",
          "Silicon",
          "Rubber",
          "Fabric",
        ],
        displayOrder: 7,
        placeholder: "Select material",
        helpText: "Primary material composition",
      },
      {
        fieldName: "Gaming Focused",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 8,
        placeholder: "Select option",
        helpText: "Is this a gaming-focused accessory?",
      },
      {
        fieldName: "Backlight",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "No Backlight",
          "Single Color LED",
          "RGB",
          "ARGB (Addressable RGB)",
        ],
        displayOrder: 9,
        placeholder: "Select backlight type",
        helpText: "Keyboard/mouse backlight options",
      },
      {
        fieldName: "Mouse Tracking Method",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Optical",
          "Laser",
          "BlueTrack",
          "Trackball",
        ],
        displayOrder: 10,
        placeholder: "Select tracking method",
        helpText: "Mouse sensor/tracking technology",
      },
      {
        fieldName: "Keyboard Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Membrane",
          "Mechanical",
          "Semi-Mechanical",
          "Chiclet",
          "Scissor Switch",
        ],
        displayOrder: 11,
        placeholder: "Select keyboard type",
        helpText: "Type of keyboard switch mechanism",
      },
      {
        fieldName: "Number of Keys",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "60% (Compact)",
          "65%",
          "75% (TKL)",
          "100% (Full Size)",
          "Numpad Only",
        ],
        displayOrder: 12,
        placeholder: "Select key layout",
        helpText: "Keyboard size and key count percentage",
      },
      {
        fieldName: "Cooling Pad Fans",
        dataType: "Integer",
        required: false,
        filterable: true,
        options: ["1", "2", "3", "4", "5", "6"],
        displayOrder: 13,
        placeholder: "Select number of fans",
        helpText: "Number of cooling fans (for cooling pads)",
      },
      {
        fieldName: "Bag Capacity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "< 20 L",
          "20 L - 30 L",
          "30 L - 40 L",
          "> 40 L",
        ],
        displayOrder: 14,
        placeholder: "Select capacity",
        helpText: "Storage capacity in liters",
      },
      {
        fieldName: "Water Resistant",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 15,
        placeholder: "Select option",
        helpText: "Is the accessory water resistant?",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 16,
        placeholder: "e.g., 1 Year Limited Hardware Warranty",
        helpText: "Warranty details and coverage",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 17,
        placeholder: "e.g., Wireless Mouse, AA Battery, USB Receiver, User Documentation",
        helpText: "Items included in the package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Network Components",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Wireless Router",
          "Modem",
          "Router + Modem (ADSL/VDSL)",
          "Range Extender / Repeater",
          "Network Switch",
          "USB Wi-Fi Adapter",
          "PCIe Network Card",
          "Wireless Access Point",
          "Mesh Wi-Fi System",
          "Mobile Wi-Fi Hotspot",
        ],
        displayOrder: 1,
        placeholder: "Select component type",
        helpText: "Type of network component",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "TP-Link",
          "D-Link",
          "Netgear",
          "Tenda",
          "Asus",
          "Cisco",
          "Mercusys",
          "Linksys",
          "Ubiquiti",
          "Digisol",
          "Huawei",
          "Zyxel",
          "Synology",
          "Google",
          "Amazon eero",
          "Mi",
          "Nokia",
          "Alcatel",
          "Airtel",
          "Jio",
          "Prolink",
          "Mikrotik",
          "Aruba",
          "Syrotech",
          "Cudy",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Network equipment manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 3,
        placeholder: "e.g., Archer C6, N300",
        helpText: "Specific model name",
      },
      {
        fieldName: "Wireless Speed",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "150 Mbps",
          "300 Mbps",
          "450 Mbps",
          "600 Mbps",
          "750 Mbps",
          "1200 Mbps (AC1200)",
          "1300 Mbps",
          "1750 Mbps",
          "1900 Mbps (AC1900)",
          "3000 Mbps (AX3000)",
          "5400 Mbps (AX5400)",
          "6000 Mbps (AX6000)",
          "11000 Mbps (AX11000)",
          "Not Applicable",
        ],
        displayOrder: 4,
        placeholder: "Select speed",
        helpText: "Maximum wireless transmission speed",
      },
      {
        fieldName: "Frequency Band",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Single Band (2.4 GHz)",
          "Dual Band (2.4 GHz + 5 GHz)",
          "Tri Band (2.4 GHz + 5 GHz + 5/6 GHz)",
          "Not Applicable",
        ],
        displayOrder: 5,
        placeholder: "Select frequency band",
        helpText: "Wi-Fi frequency band support",
      },
      {
        fieldName: "Wireless Standard",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "IEEE 802.11b/g/n (Wi-Fi 4)",
          "IEEE 802.11ac (Wi-Fi 5)",
          "IEEE 802.11ax (Wi-Fi 6)",
          "IEEE 802.11ax (Wi-Fi 6E)",
          "IEEE 802.11be (Wi-Fi 7)",
          "Not Applicable",
        ],
        displayOrder: 6,
        placeholder: "Select standard",
        helpText: "Wi-Fi standard/protocol support",
      },
      {
        fieldName: "Broadband Compatibility",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Ethernet Cable (RJ45)",
          "ADSL (RJ11 Phone Line)",
          "SIM Card Slot (4G/5G)",
          "USB Dongle Support",
        ],
        displayOrder: 7,
        placeholder: "Select compatibility",
        helpText: "Broadband connection types supported",
      },
      {
        fieldName: "Number of Antennas",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Internal",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "8",
          "> 8",
        ],
        displayOrder: 8,
        placeholder: "Select antenna count",
        helpText: "Number of antennas for signal strength",
      },
      {
        fieldName: "Number of LAN Ports",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "0",
          "1",
          "2",
          "3",
          "4",
          "5",
          "8",
          "16",
          "24",
          "48",
        ],
        displayOrder: 9,
        placeholder: "Select port count",
        helpText: "Number of Ethernet LAN ports",
      },
      {
        fieldName: "Number of USB Ports",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "0",
          "1",
          "2",
        ],
        displayOrder: 10,
        placeholder: "Select USB port count",
        helpText: "Number of USB ports available",
      },
      {
        fieldName: "Encryption / Security",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "WPA",
          "WPA2",
          "WPA3",
          "WEP",
          "WPS Support",
        ],
        displayOrder: 11,
        placeholder: "Select security protocol",
        helpText: "Wireless security encryption standards",
      },
      {
        fieldName: "Switch Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Unmanaged",
          "Managed",
          "Smart Managed",
          "PoE (Power over Ethernet)",
          "Not Applicable",
        ],
        displayOrder: 12,
        placeholder: "Select switch type",
        helpText: "Type of network switch (for switch products)",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "White",
          "Black",
          "Grey",
          "Blue",
          "Silver",
        ],
        displayOrder: 13,
        placeholder: "Select a color",
        helpText: "Device color/finish",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 14,
        placeholder: "e.g., 3 Years Manufacturer Warranty",
        helpText: "Warranty details and coverage",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 15,
        placeholder: "e.g., Router, Power Adapter, RJ45 Ethernet Cable, Installation Guide",
        helpText: "Items included in the package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Computer Peripherals",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Printer",
          "Monitor",
          "Projector",
          "UPS",
          "Scanner",
          "Webcam",
          "Barcode Scanner",
          "Biometric Device",
          "Graphics Tablet",
          "KVM Switch",
          "Lamination Machine",
          "Note Counting Machine",
          "Receipt Printer",
          "3D Printer",
        ],
        displayOrder: 1,
        placeholder: "Select peripheral type",
        helpText: "Type of computer peripheral",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "HP",
          "Canon",
          "Epson",
          "Dell",
          "Samsung",
          "LG",
          "Acer",
          "BenQ",
          "Brother",
          "ViewSonic",
          "APC",
          "Microtek",
          "Luminous",
          "V-Guard",
          "Zebra",
          "Honeywell",
          "TVS Electronics",
          "Logitech",
          "Zebronics",
          "Fingers",
          "Secureye",
          "Hikvision",
          "CP Plus",
          "Pantum",
          "Ricoh",
          "Kyocera",
          "Konica Minolta",
          "Xerox",
          "Gigabyte",
          "MSI",
          "Asus",
          "Lenovo",
          "AOC",
          "EGate",
          "Wanbo",
          "Wacom",
          "Huion",
          "XP-Pen",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Peripheral manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 3,
        placeholder: "e.g., LaserJet Pro M126nw, 24MP88HV",
        helpText: "Specific model name",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "White",
          "Grey",
          "Silver",
          "Blue",
          "Red",
          "Dual Tone",
        ],
        displayOrder: 4,
        placeholder: "Select a color",
        helpText: "Peripheral color/finish",
      },
      {
        fieldName: "Connectivity Interface",
        dataType: "Multi-Select",
        required: true,
        filterable: true,
        options: [
          "USB",
          "Wireless (Wi-Fi)",
          "Ethernet (LAN)",
          "Bluetooth",
          "HDMI",
          "VGA",
          "DisplayPort",
          "DVI",
          "ThunderBolt",
          "Audio Jack",
          "Serial Port",
          "Parallel Port",
        ],
        displayOrder: 5,
        placeholder: "Select connectivity options",
        helpText: "Available connection interfaces",
      },
      {
        fieldName: "Printer Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Laser",
          "Inkjet",
          "Ink Tank",
          "Dot Matrix",
          "Thermal",
          "3D",
        ],
        displayOrder: 6,
        placeholder: "Select printer type",
        helpText: "Type of printer technology",
      },
      {
        fieldName: "Printer Functions",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Print Only",
          "Multi-function (Print, Scan, Copy)",
          "Multi-function (Print, Scan, Copy, Fax)",
        ],
        displayOrder: 7,
        placeholder: "Select functions",
        helpText: "Printer capabilities",
      },
      {
        fieldName: "Printer Output",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Monochrome (Black & White)",
          "Color",
        ],
        displayOrder: 8,
        placeholder: "Select output type",
        helpText: "Color or monochrome output",
      },
      {
        fieldName: "Print Speed (PPM)",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "< 10 PPM",
          "10-20 PPM",
          "21-30 PPM",
          "> 30 PPM",
        ],
        displayOrder: 9,
        placeholder: "Select print speed",
        helpText: "Pages per minute printing speed",
      },
      {
        fieldName: "Refill Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Ink Cartridge",
          "Toner Cartridge",
          "Ink Bottle",
          "Ribbon",
          "Filament (3D)",
        ],
        displayOrder: 10,
        placeholder: "Select refill type",
        helpText: "Type of consumable used",
      },
      {
        fieldName: "Page Size Supported",
        dataType: "Multi-Select",
        required: false,
        filterable: true,
        options: [
          "A4",
          "A3",
          "Legal",
          "Letter",
          "Envelope",
          "A5",
          "A6",
          "4x6 Photos",
        ],
        displayOrder: 11,
        placeholder: "Select supported sizes",
        helpText: "Paper sizes the printer can handle",
      },
      {
        fieldName: "Monitor Screen Size",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "18.5 inch",
          "19.5 inch",
          "21.5 inch",
          "22 inch",
          "23.8 inch",
          "24 inch",
          "27 inch",
          "32 inch",
          "34 inch",
          "> 34 inch",
        ],
        displayOrder: 12,
        placeholder: "Select screen size",
        helpText: "Monitor display diagonal size",
      },
      {
        fieldName: "Monitor Resolution",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "HD (1366 x 768)",
          "HD+ (1600 x 900)",
          "Full HD (1920 x 1080)",
          "2K QHD (2560 x 1440)",
          "4K UHD (3840 x 2160)",
          "5K",
          "8K",
        ],
        displayOrder: 13,
        placeholder: "Select resolution",
        helpText: "Display pixel resolution",
      },
      {
        fieldName: "Monitor Panel Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "IPS",
          "VA",
          "TN",
          "OLED",
          "AMOLED",
          "QLED",
          "Mini-LED",
        ],
        displayOrder: 14,
        placeholder: "Select panel type",
        helpText: "Monitor panel technology",
      },
      {
        fieldName: "Refresh Rate",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "60Hz",
          "75Hz",
          "100Hz",
          "120Hz",
          "144Hz",
          "165Hz",
          "240Hz",
          "360Hz",
        ],
        displayOrder: 15,
        placeholder: "Select refresh rate",
        helpText: "Display refresh rate for smooth visuals",
      },
      {
        fieldName: "Response Time",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "0.5 ms",
          "1 ms",
          "2 ms",
          "4 ms",
          "5 ms",
          "> 5 ms",
        ],
        displayOrder: 16,
        placeholder: "Select response time",
        helpText: "Panel response time for gaming",
      },
      {
        fieldName: "Curved Screen",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 17,
        placeholder: "Select option",
        helpText: "Is the screen curved?",
      },
      {
        fieldName: "Projector Brightness",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "< 1000 Lumens",
          "1000-3000 Lumens",
          "3000-4000 Lumens",
          "> 4000 Lumens",
        ],
        displayOrder: 18,
        placeholder: "Select brightness",
        helpText: "Projector brightness level in lumens",
      },
      {
        fieldName: "Projector Projection Distance",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Short Throw (< 1m)",
          "Standard Throw (1-3m)",
          "Long Throw (> 3m)",
        ],
        displayOrder: 19,
        placeholder: "Select throw distance",
        helpText: "Recommended projection distance",
      },
      {
        fieldName: "Scanner Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Flatbed",
          "Sheetfed",
          "Handheld",
          "Overhead",
        ],
        displayOrder: 20,
        placeholder: "Select scanner type",
        helpText: "Type of document scanner",
      },
      {
        fieldName: "UPS Capacity (VA)",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "600 VA",
          "650 VA",
          "800 VA",
          "1000 VA",
          "1100 VA",
          "1500 VA",
          "2000 VA",
          "> 2000 VA",
        ],
        displayOrder: 21,
        placeholder: "Select capacity",
        helpText: "UPS power capacity in VA",
      },
      {
        fieldName: "Webcam Resolution",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "720p (HD)",
          "1080p (Full HD)",
          "2K",
          "4K",
        ],
        displayOrder: 22,
        placeholder: "Select resolution",
        helpText: "Webcam video recording resolution",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 23,
        placeholder: "e.g., 3 Years Onsite Warranty",
        helpText: "Warranty details and coverage",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 24,
        placeholder: "e.g., Monitor, Stand, HDMI Cable, Power Cord, Manual",
        helpText: "Items included in the package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Software",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Antivirus & Security",
          "Operating System",
          "Office & Productivity",
          "Accounting & Finance",
          "Business & Legal",
          "Graphic & Video Editing",
          "Educational",
          "Gaming Software",
          "Utility & Tuning",
          "Server Software",
          "Developer Tools",
        ],
        displayOrder: 1,
        placeholder: "Select software type",
        helpText: "Category of software product",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Microsoft",
          "McAfee",
          "Quick Heal",
          "Kaspersky",
          "Norton",
          "Bitdefender",
          "Adobe",
          "Tally",
          "K7 Computing",
          "ESET",
          "Trend Micro",
          "Avast",
          "AVG",
          "Net Protector (NPAV)",
          "Corel",
          "Autodesk",
          "Sentinel",
          "Symantec",
          "Guardian",
          "Wondershare",
          "Nero",
          "CyberLink",
          "EaseUS",
          "IObit",
          "WinZip",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Software publisher/brand",
      },
      {
        fieldName: "Edition",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Standard",
          "Professional",
          "Home",
          "Home & Student",
          "Premium",
          "Ultimate",
          "Business",
          "Enterprise",
          "Total Security",
          "Internet Security",
          "Antivirus Pro",
          "Gold",
          "Platinum",
        ],
        displayOrder: 3,
        placeholder: "Select edition",
        helpText: "Software edition/version tier",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 4,
        placeholder: "e.g., Windows 11 Pro, Office 2021, Total Security",
        helpText: "Specific product name/model",
      },
      {
        fieldName: "Architecture",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "64-bit",
          "32-bit",
          "32-bit & 64-bit (Both)",
        ],
        displayOrder: 5,
        placeholder: "Select architecture",
        helpText: "System architecture support",
      },
      {
        fieldName: "Format",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Email Delivery (Digital Key)",
          "CD/DVD",
          "USB Flash Drive",
          "Key Card",
        ],
        displayOrder: 6,
        placeholder: "Select delivery format",
        helpText: "How the software is delivered",
      },
      {
        fieldName: "License Duration",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "1 Year",
          "2 Years",
          "3 Years",
          "5 Years",
          "Lifetime / Perpetual",
          "Subscription (Monthly)",
          "Subscription (Annual)",
        ],
        displayOrder: 7,
        placeholder: "Select license duration",
        helpText: "How long the license is valid",
      },
      {
        fieldName: "Number of Users/Devices",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "1 User",
          "2 Users",
          "3 Users",
          "5 Users",
          "10 Users",
          "10+ Users",
          "Unlimited",
        ],
        displayOrder: 8,
        placeholder: "Select user/device count",
        helpText: "Number of installations allowed",
      },
      {
        fieldName: "Operating System",
        dataType: "Multi-Select",
        required: true,
        filterable: true,
        options: [
          "Windows 11",
          "Windows 10",
          "Windows 8.1",
          "Windows 8",
          "Windows 7",
          "macOS",
          "Android",
          "iOS",
          "Linux",
          "Windows Server",
        ],
        displayOrder: 9,
        placeholder: "Select compatible OS",
        helpText: "Operating systems the software runs on",
      },
      {
        fieldName: "Version",
        dataType: "Text",
        required: false,
        filterable: true,
        displayOrder: 10,
        placeholder: "e.g., 2024, 21.0, v11",
        helpText: "Software version number",
      },
      {
        fieldName: "Language",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "English",
          "Hindi",
          "Multilingual",
          "Regional Languages",
        ],
        displayOrder: 11,
        placeholder: "Select language",
        helpText: "Interface language support",
      },
      {
        fieldName: "System Requirements",
        dataType: "Text",
        required: false,
        filterable: false,
        displayOrder: 12,
        placeholder: "e.g., 4GB RAM, 10GB HDD space",
        helpText: "Minimum hardware requirements",
      },
      {
        fieldName: "Features",
        dataType: "Multi-Select",
        required: false,
        filterable: true,
        options: [
          "Ransomware Protection",
          "Parental Control",
          "Banking Protection",
          "Firewall",
          "VPN Included",
          "PC Tune-up",
          "Cloud Storage",
          "Multi-Device Support",
        ],
        displayOrder: 13,
        placeholder: "Select features",
        helpText: "Key software features",
      },
      {
        fieldName: "Media Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Retail Box",
          "OEM (Original Equipment Manufacturer)",
          "Digital Download",
        ],
        displayOrder: 14,
        placeholder: "Select media type",
        helpText: "Type of software package",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Computer Components",
    fields: [
      {
        fieldName: "Component Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Processor",
          "Motherboard",
          "Graphic Card",
          "Desktop RAM",
          "Laptop RAM",
          "Internal SSD",
          "Internal HDD",
          "Power Supply Unit (PSU)",
          "Computer Cabinet",
          "CPU Cooler",
          "Cabinet Fan",
          "Thermal Paste",
        ],
        displayOrder: 1,
        placeholder: "Select component type",
        helpText: "Type of computer component",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Intel",
          "AMD",
          "NVIDIA",
          "Asus",
          "MSI",
          "Gigabyte",
          "ASRock",
          "Zotac",
          "Galax",
          "Inno3D",
          "Corsair",
          "Kingston",
          "HyperX",
          "Crucial",
          "Adata",
          "XPG",
          "Western Digital",
          "Seagate",
          "Samsung",
          "Cooler Master",
          "Deepcool",
          "Lian Li",
          "NZXT",
          "Ant Esports",
          "Circle",
          "Zebronics",
          "Consistent",
          "Finger",
          "G.Skill",
          "TeamGroup",
          "Thermaltake",
          "EVGA",
          "Sapphire",
          "PowerColor",
          "PNY",
          "Colorful",
          "Biostar",
          "Noctua",
          "Arctic",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Component manufacturer",
      },
      {
        fieldName: "Processor Brand",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Intel",
          "AMD",
        ],
        displayOrder: 3,
        placeholder: "Select processor brand",
        helpText: "Processor manufacturer (for CPU components)",
      },
      {
        fieldName: "Processor Name",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Core i3",
          "Core i5",
          "Core i7",
          "Core i9",
          "Core Ultra 5",
          "Core Ultra 7",
          "Core Ultra 9",
          "Ryzen 3",
          "Ryzen 5",
          "Ryzen 7",
          "Ryzen 9",
          "Ryzen Threadripper",
          "Pentium Gold",
          "Athlon",
          "Celeron",
        ],
        displayOrder: 4,
        placeholder: "Select processor model",
        helpText: "Processor series/model",
      },
      {
        fieldName: "Processor Generation",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "14th Gen",
          "13th Gen",
          "12th Gen",
          "11th Gen",
          "10th Gen",
          "Ryzen 9000 Series",
          "Ryzen 8000 Series",
          "Ryzen 7000 Series",
          "Ryzen 5000 Series",
          "Ryzen 4000 Series",
        ],
        displayOrder: 5,
        placeholder: "Select generation",
        helpText: "Processor generation/series",
      },
      {
        fieldName: "Socket Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "LGA 1700",
          "LGA 1200",
          "LGA 1151",
          "AM5",
          "AM4",
          "TR4",
          "TRX40",
          "sTR5",
        ],
        displayOrder: 6,
        placeholder: "Select socket type",
        helpText: "CPU socket compatibility",
      },
      {
        fieldName: "Motherboard Form Factor",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "ATX",
          "Micro-ATX",
          "Mini-ITX",
          "E-ATX",
        ],
        displayOrder: 7,
        placeholder: "Select form factor",
        helpText: "Motherboard size and layout",
      },
      {
        fieldName: "Chipset",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Z790",
          "B760",
          "H610",
          "X670",
          "X670E",
          "B650",
          "B650E",
          "A620",
          "Z690",
          "B660",
          "X570",
          "B550",
          "A520",
          "H510",
          "H410",
        ],
        displayOrder: 8,
        placeholder: "Select chipset",
        helpText: "Motherboard chipset model",
      },
      {
        fieldName: "Graphics Chipset",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVIDIA",
          "AMD",
          "Intel",
        ],
        displayOrder: 9,
        placeholder: "Select GPU chipset",
        helpText: "Graphics card manufacturer",
      },
      {
        fieldName: "Graphics Memory",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "2GB",
          "4GB",
          "6GB",
          "8GB",
          "10GB",
          "12GB",
          "16GB",
          "20GB",
          "24GB",
        ],
        displayOrder: 10,
        placeholder: "Select GPU memory",
        helpText: "Video RAM capacity",
      },
      {
        fieldName: "GPU Model",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "GeForce RTX 4090",
          "RTX 4080 Super",
          "RTX 4080",
          "RTX 4070 Ti Super",
          "RTX 4070 Ti",
          "RTX 4070 Super",
          "RTX 4070",
          "RTX 4060 Ti",
          "RTX 4060",
          "RTX 3060",
          "GTX 1650",
          "Radeon RX 7900 XTX",
          "RX 7900 XT",
          "RX 7800 XT",
          "RX 7700 XT",
          "RX 7600",
          "RX 6600",
          "Intel Arc A770",
          "Intel Arc A750",
        ],
        displayOrder: 11,
        placeholder: "Select GPU model",
        helpText: "Specific graphics card model",
      },
      {
        fieldName: "Memory (RAM) Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "DDR5",
          "DDR4",
          "DDR3",
        ],
        displayOrder: 12,
        placeholder: "Select RAM type",
        helpText: "Type of RAM technology",
      },
      {
        fieldName: "RAM Capacity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "4GB",
          "8GB",
          "16GB",
          "32GB",
          "64GB",
          "Kit (8GBx2)",
          "Kit (16GBx2)",
          "Kit (32GBx2)",
        ],
        displayOrder: 13,
        placeholder: "Select RAM capacity",
        helpText: "Amount of RAM",
      },
      {
        fieldName: "RAM Speed",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "2400 MHz",
          "2666 MHz",
          "3000 MHz",
          "3200 MHz",
          "3600 MHz",
          "4800 MHz",
          "5200 MHz",
          "5600 MHz",
          "6000 MHz",
          "6400 MHz",
          "7200 MHz",
        ],
        displayOrder: 14,
        placeholder: "Select RAM speed",
        helpText: "RAM frequency/speed",
      },
      {
        fieldName: "Storage Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVMe M.2 SSD",
          "SATA SSD",
          "HDD (Hard Disk Drive)",
        ],
        displayOrder: 15,
        placeholder: "Select storage type",
        helpText: "Type of storage device",
      },
      {
        fieldName: "Storage Capacity",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "120GB",
          "240GB",
          "250GB",
          "256GB",
          "480GB",
          "500GB",
          "512GB",
          "1TB",
          "2TB",
          "4TB",
          "8TB",
          "10TB",
          "12TB",
          "16TB",
          "18TB",
          "20TB",
        ],
        displayOrder: 16,
        placeholder: "Select storage capacity",
        helpText: "Storage device capacity",
      },
      {
        fieldName: "HDD Interface",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "SATA 6.0 Gb/s",
          "SAS",
        ],
        displayOrder: 17,
        placeholder: "Select interface",
        helpText: "Hard drive interface type",
      },
      {
        fieldName: "HDD RPM",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "5400 RPM",
          "7200 RPM",
        ],
        displayOrder: 18,
        placeholder: "Select RPM",
        helpText: "Hard drive speed (rotations per minute)",
      },
      {
        fieldName: "PSU Wattage",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "450W",
          "550W",
          "650W",
          "750W",
          "850W",
          "1000W",
          "1200W",
          "1300W",
          "1600W",
        ],
        displayOrder: 19,
        placeholder: "Select wattage",
        helpText: "Power supply unit wattage",
      },
      {
        fieldName: "PSU Certification",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "80 Plus White",
          "80 Plus Bronze",
          "80 Plus Silver",
          "80 Plus Gold",
          "80 Plus Platinum",
          "80 Plus Titanium",
          "Non-Certified",
        ],
        displayOrder: 20,
        placeholder: "Select certification",
        helpText: "PSU efficiency certification level",
      },
      {
        fieldName: "Modular PSU",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Fully Modular",
          "Semi-Modular",
          "Non-Modular",
        ],
        displayOrder: 21,
        placeholder: "Select modularity",
        helpText: "Power supply modularity type",
      },
      {
        fieldName: "Cabinet Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Mid Tower",
          "Full Tower",
          "Mini Tower",
          "Cube Case",
        ],
        displayOrder: 22,
        placeholder: "Select case type",
        helpText: "Computer cabinet/chassis type",
      },
      {
        fieldName: "Side Panel",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Tempered Glass",
          "Acrylic",
          "Metal",
          "Mesh",
        ],
        displayOrder: 23,
        placeholder: "Select panel type",
        helpText: "Side panel material",
      },
      {
        fieldName: "Cooler Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Air Cooler",
          "AIO Liquid Cooler (120mm)",
          "AIO Liquid Cooler (240mm)",
          "AIO Liquid Cooler (360mm)",
          "Custom Loop",
        ],
        displayOrder: 24,
        placeholder: "Select cooler type",
        helpText: "CPU cooler type and cooling method",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 25,
        placeholder: "e.g., 3 Years Domestic Warranty",
        helpText: "Warranty details and coverage",
      },
    ],
  },
  {
    mainCategory: "Electronics",
    subCategory: "Computers",
    subSubCategory: "Desktop PCs",
    fields: [
      {
        fieldName: "Type",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "All-in-One",
          "Tower PC",
          "Mini PC",
          "Gaming Desktop",
          "Stick PC",
          "Tiny Desktop",
          "Workstation",
        ],
        displayOrder: 1,
        placeholder: "Select desktop type",
        helpText: "Type of desktop computer",
      },
      {
        fieldName: "Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "HP",
          "Dell",
          "Lenovo",
          "Apple",
          "Asus",
          "Acer",
          "MSI",
          "Intel",
          "Zotac",
          "Gigabyte",
          "Raspberry Pi",
          "Zebronics",
          "Micromax",
          "iBall",
          "RiPC",
          "Entwino",
          "Frontech",
          "Quantum",
          "Assembled",
          "CHUWI",
          "Beelink",
          "Minisforum",
        ],
        displayOrder: 2,
        placeholder: "Select a brand",
        helpText: "Desktop computer manufacturer",
      },
      {
        fieldName: "Model Name",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 3,
        placeholder: "e.g., iMac 24-inch, Inspiron 24 5000, IdeaCentre AIO 3",
        helpText: "Specific model name",
      },
      {
        fieldName: "Processor Brand",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Intel",
          "AMD",
          "Apple M-Series",
        ],
        displayOrder: 4,
        placeholder: "Select processor brand",
        helpText: "Processor manufacturer",
      },
      {
        fieldName: "Processor Name",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Core i3",
          "Core i5",
          "Core i7",
          "Core i9",
          "Core Ultra 5",
          "Core Ultra 7",
          "Core Ultra 9",
          "Ryzen 3",
          "Ryzen 5",
          "Ryzen 7",
          "Ryzen 9",
          "Ryzen Threadripper",
          "Apple M1",
          "Apple M3",
          "Apple M3 Pro",
          "Apple M3 Max",
          "Apple M4",
          "Pentium Gold",
          "Pentium Silver",
          "Celeron",
          "Athlon",
        ],
        displayOrder: 5,
        placeholder: "Select processor model",
        helpText: "Processor series/model",
      },
      {
        fieldName: "Processor Generation",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "14th Gen",
          "13th Gen",
          "12th Gen",
          "11th Gen",
          "10th Gen",
          "Ryzen 8000 Series",
          "Ryzen 7000 Series",
          "Ryzen 5000 Series",
          "Not Applicable",
        ],
        displayOrder: 6,
        placeholder: "Select generation",
        helpText: "Processor generation/series",
      },
      {
        fieldName: "RAM Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "2GB",
          "4GB",
          "8GB",
          "12GB",
          "16GB",
          "32GB",
          "64GB",
          "128GB",
        ],
        displayOrder: 7,
        placeholder: "Select RAM capacity",
        helpText: "Amount of RAM (Random Access Memory)",
      },
      {
        fieldName: "RAM Type",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "DDR5",
          "DDR4",
          "DDR3",
          "LPDDR4",
          "LPDDR4X",
          "Unified Memory",
        ],
        displayOrder: 8,
        placeholder: "Select RAM type",
        helpText: "Type of RAM technology",
      },
      {
        fieldName: "SSD Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "128GB",
          "256GB",
          "512GB",
          "1TB",
          "2TB",
          "4TB",
          "No SSD",
        ],
        displayOrder: 9,
        placeholder: "Select SSD capacity",
        helpText: "SSD storage capacity",
      },
      {
        fieldName: "HDD Capacity",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "500GB",
          "1TB",
          "2TB",
          "4TB",
          "No HDD",
        ],
        displayOrder: 10,
        placeholder: "Select HDD capacity",
        helpText: "HDD storage capacity",
      },
      {
        fieldName: "Operating System",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Windows 11 Home",
          "Windows 11 Pro",
          "Windows 10 Home",
          "Windows 10 Pro",
          "macOS Sonoma",
          "macOS Ventura",
          "DOS",
          "Ubuntu",
          "Linux",
          "Chrome OS",
          "Endless OS",
        ],
        displayOrder: 11,
        placeholder: "Select OS",
        helpText: "Operating system",
      },
      {
        fieldName: "Graphic Processor Brand",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVIDIA",
          "AMD",
          "Intel",
          "Apple (Integrated)",
        ],
        displayOrder: 12,
        placeholder: "Select GPU brand",
        helpText: "Graphics processor manufacturer",
      },
      {
        fieldName: "Graphic Processor Series",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "NVIDIA GeForce RTX 4090",
          "RTX 4080",
          "RTX 4070",
          "RTX 4060",
          "RTX 3060",
          "RTX 3050",
          "GTX 1650",
          "GTX 1660 Super",
          "AMD Radeon RX 7000 Series",
          "AMD Radeon RX 6000 Series",
          "Intel Arc Graphics",
          "Intel UHD Graphics",
          "Intel Iris Xe Graphics",
        ],
        displayOrder: 13,
        placeholder: "Select GPU series",
        helpText: "Specific graphics card model",
      },
      {
        fieldName: "Dedicated Graphic Memory",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Integrated",
          "2GB",
          "4GB",
          "6GB",
          "8GB",
          "10GB",
          "12GB",
          "16GB",
          "24GB",
        ],
        displayOrder: 14,
        placeholder: "Select GPU memory",
        helpText: "Amount of dedicated graphics memory (VRAM)",
      },
      {
        fieldName: "Screen Size",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Not Applicable (Tower/Mini)",
          "19.5 inch",
          "21.5 inch",
          "23.8 inch",
          "24 inch",
          "27 inch",
          "32 inch",
          "34 inch",
        ],
        displayOrder: 15,
        placeholder: "Select screen size",
        helpText: "Display diagonal size (for All-in-One models)",
      },
      {
        fieldName: "Screen Resolution",
        dataType: "Select",
        required: false,
        filterable: true,
        options: [
          "Not Applicable",
          "Full HD (1920 x 1080)",
          "Quad HD (2560 x 1440)",
          "4K Ultra HD (3840 x 2160)",
          "4.5K Retina",
          "5K Retina",
        ],
        displayOrder: 16,
        placeholder: "Select resolution",
        helpText: "Display pixel resolution",
      },
      {
        fieldName: "Touchscreen",
        dataType: "Select",
        required: false,
        filterable: true,
        options: ["Yes", "No"],
        displayOrder: 17,
        placeholder: "Select option",
        helpText: "Does the desktop have a touchscreen?",
      },
      {
        fieldName: "Monitor Included",
        dataType: "Select",
        required: true,
        filterable: true,
        options: ["Yes", "No (CPU Only)"],
        displayOrder: 18,
        placeholder: "Select option",
        helpText: "Is a monitor included with the desktop?",
      },
      {
        fieldName: "Color",
        dataType: "Select",
        required: true,
        filterable: true,
        options: [
          "Black",
          "White",
          "Silver",
          "Grey",
          "Blue",
          "Green",
          "Pink",
          "Purple",
          "Orange",
          "Yellow",
          "Multicolor",
        ],
        displayOrder: 19,
        placeholder: "Select a color",
        helpText: "Desktop color/finish",
      },
      {
        fieldName: "Warranty Summary",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 20,
        placeholder: "e.g., 3 Years Onsite Warranty",
        helpText: "Warranty details and coverage",
      },
      {
        fieldName: "In The Box",
        dataType: "Text",
        required: true,
        filterable: false,
        displayOrder: 21,
        placeholder: "e.g., All-in-One PC, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
        helpText: "Items included in the package",
      },
    ],
  },
];

async function seedCategoryAttributes() {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await mongoose.connect(process.env.MONGO_URI);

    console.log("🗑️  Clearing existing attributes...");
    await CategoryAttribute.deleteMany({});

    console.log("📝 Seeding category attributes...\n");

    let totalAttributes = 0;

    for (const category of CATEGORY_ATTRIBUTES) {
      const result = await CategoryAttribute.create({
        mainCategory: category.mainCategory,
        subCategory: category.subCategory,
        subSubCategory: category.subSubCategory,
        fields: category.fields,
        isActive: true,
      });

      console.log(
        `✅ ${category.mainCategory} > ${category.subCategory} > ${category.subSubCategory}`
      );
      console.log(`   📊 Fields: ${category.fields.length}`);

      // Count filterable and required fields
      const filterableCount = category.fields.filter((f) => f.filterable).length;
      const requiredCount = category.fields.filter((f) => f.required).length;

      console.log(`   🔍 Filterable: ${filterableCount}, Required: ${requiredCount}\n`);

      totalAttributes += category.fields.length;
    }

    console.log("═══════════════════════════════════════════════════════════════");
    console.log("✅ CATEGORY ATTRIBUTES SEEDING COMPLETED!");
    console.log("═══════════════════════════════════════════════════════════════\n");

    console.log(`📊 Summary:`);
    console.log(`   • Total Categories with Attributes: ${CATEGORY_ATTRIBUTES.length}`);
    console.log(`   • Total Fields: ${totalAttributes}`);
    console.log(`   • Average Fields per Category: ${(totalAttributes / CATEGORY_ATTRIBUTES.length).toFixed(1)}\n`);

    // Show stats by data type
    const typeStats = {};
    CATEGORY_ATTRIBUTES.forEach((cat) => {
      cat.fields.forEach((field) => {
        typeStats[field.dataType] = (typeStats[field.dataType] || 0) + 1;
      });
    });

    console.log(`📈 Fields by Data Type:`);
    Object.entries(typeStats).forEach(([type, count]) => {
      console.log(`   • ${type}: ${count} fields`);
    });

    // Show filterable stats
    const filterableFields = [];
    const requiredFields = [];
    CATEGORY_ATTRIBUTES.forEach((cat) => {
      cat.fields.forEach((field) => {
        if (field.filterable) filterableFields.push(field.fieldName);
        if (field.required) requiredFields.push(field.fieldName);
      });
    });

    console.log(`\n🔍 Filterable Fields: ${filterableFields.length}`);
    console.log(`   Fields: ${filterableFields.join(", ")}`);

    console.log(`\n✔️  Required Fields: ${requiredFields.length}`);
    console.log(`   Fields: ${requiredFields.join(", ")}`);

    console.log("\n✨ Ready to use! Fetch attributes via API:");
    console.log("   GET /api/attributes/category/:mainCategory/:subCategory/:subSubCategory");
    console.log("   GET /api/attributes/filterable/:mainCategory/:subCategory/:subSubCategory\n");

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding attributes:", error);
    process.exit(1);
  }
}

seedCategoryAttributes();
